application:
  subdomain: pindou
  oidc_redirect_path: /api/auth/oidc/callback
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://pindou:8080/

services:
  pindou:
    # upstream: czyt/pindou:0.5.8
    image: docker.1ms.run/czyt/pindou:0.5.8
    user: root
    environment:
      - PORT=8080
      - DATABASE_PATH=/app/data/pindou.db
      - SESSION_SECRET={{ stable_secret "session_secret" }}
      - PINDOU_OIDC_CLIENT_ID=${LAZYCAT_AUTH_OIDC_CLIENT_ID}
      - PINDOU_OIDC_CLIENT_SECRET=${LAZYCAT_AUTH_OIDC_CLIENT_SECRET}
      - PINDOU_OIDC_AUTH_URI=${LAZYCAT_AUTH_OIDC_AUTH_URI}
      - PINDOU_OIDC_TOKEN_URI=${LAZYCAT_AUTH_OIDC_TOKEN_URI}
      - PINDOU_OIDC_USERINFO_URI=${LAZYCAT_AUTH_OIDC_USERINFO_URI}
      - PINDOU_APP_URL=https://${LAZYCAT_APP_DOMAIN}
      - PINDOU_OIDC_CALLBACK_PATH=/api/auth/oidc/callback
    binds:
      - /lzcapp/var/pindou:/app/data
